name: Daily Bday Check

on:
  schedule:
    - cron: "31 18 * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Bun & run
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Debug ENV
        run: |
          echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}"

      - name: Check and send bday wishes
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
        run: |
          bun i
          bun run check
